import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { Activity, AlertTriangle, Boxes, ClipboardList, HeartPulse, LayoutDashboard, Leaf, Menu, Plus, RotateCcw, X } from "lucide-react";
import { useState } from "react";
import { useEstoque } from "@/app/EstoqueContext";
import { Button } from "@/components/ui";
const links=[['/','Visão geral',LayoutDashboard],['/estoque','Estoque atual',Boxes],['/lotes','Lotes e validade',ClipboardList],['/movimentacoes','Movimentações',Activity],['/alertas','Alertas',AlertTriangle],['/status','Status técnico',HeartPulse],['/repositorio','Repositório',Leaf]] as const;
export function AppLayout(){const [open,setOpen]=useState(false);const nav=useNavigate();const {erro,restaurar}=useEstoque();const reset=()=>{if(confirm("Restaurar os dados demonstrativos? Todos os registros locais deste protótipo serão substituídos."))restaurar()};return <div className="min-h-screen bg-[#f7f6f1] text-slate-800">
  <header className="sticky top-0 z-30 flex h-16 items-center border-b border-emerald-900/10 bg-white/95 px-4 backdrop-blur lg:pl-72"><button className="mr-3 lg:hidden" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Menu/></button><div className="flex flex-1 items-center justify-between gap-3"><div><p className="font-bold text-emerald-950">Farmácia Viva – CREMIC</p><p className="text-xs text-slate-500">Protótipo PET-Saúde · dados locais demonstrativos</p></div><Button onClick={()=>nav('/movimentacoes/nova')}><Plus size={17}/><span className="hidden sm:inline">Registrar movimentação</span></Button></div></header>
  {open&&<button className="fixed inset-0 z-40 bg-black/30 lg:hidden" onClick={()=>setOpen(false)} aria-label="Fechar menu"/>}
  <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-[#123c2d] text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex h-20 items-center gap-3 border-b border-white/10 px-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-200 text-emerald-950"><HeartPulse/></div><div><strong>Farmácia</strong><p className="text-xs text-emerald-200">CREMIC</p></div><button className="ml-auto lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="space-y-1 p-3">{links.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${isActive?'bg-white text-emerald-950':'text-emerald-50 hover:bg-white/10'}`}><Icon size={18}/>{label}</NavLink>)}</nav><div className="absolute bottom-0 w-full border-t border-white/10 p-4"><button onClick={reset} className="flex items-center gap-2 text-xs text-emerald-100 hover:text-white"><RotateCcw size={14}/>Restaurar dados de demonstração</button></div></aside>
  <main className="p-4 lg:ml-64 lg:p-7">{erro?<div className="mx-auto max-w-xl rounded-2xl border border-red-200 bg-white p-8 text-center"><AlertTriangle className="mx-auto mb-3 text-red-700"/><h1 className="text-xl font-bold">Dados locais indisponíveis</h1><p className="my-3 text-sm text-slate-600">{erro}</p><Button onClick={reset}>Restaurar demonstração</Button></div>:<Outlet/>}</main>
 </div>}
